// Centralized configuration and thresholds

export const FETCH = {
  PAGE_TIMEOUT_MS: 15000,
  HEAD_TIMEOUT_MS: 8000,
  LINK_CHECK_TIMEOUT_MS: 6000,
  INDEXING_TIMEOUT_MS: 5000,
};

export const SEO = {
  TITLE_MIN_CHARS: 20,
  TITLE_MAX_CHARS: 60,
  DESC_MIN_CHARS: 70,
  DESC_MAX_CHARS: 160,
};

export const PERFORMANCE = {
  RESPONSE_FAST_MS: 500,
  RESPONSE_SLOW_MS: 1500,
  SIZE_OK_KB: 100,
  SIZE_WARN_KB: 300,
  SCRIPTS_FAIL_COUNT: 15,
  SCRIPTS_WARN_COUNT: 8,
  CSS_WARN_COUNT: 8,
  IMAGES_LAZY_WARN_COUNT: 5,
  IMAGES_DIMENSION_WARN_COUNT: 3,
};

export const LINKS = {
  MAX_LINKS_DEFAULT: 10,
  MAX_LINKS_VERBOSE: 25,
};
